from pathlib import Path

class Picture:
    data: bytes
    type: int
    mime: str
    desc: str

class FLAC:
    pictures: list[Picture]
    def __init__(self, path: str | Path) -> None: ...
    def add_picture(self, pic: Picture) -> None: ...
    def clear_pictures(self) -> None: ...
    def delete(self) -> None: ...
    def clear(self) -> None: ...
    def save(self) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> list[str]: ...
    def __setitem__(self, key: str, value: str | list[str]) -> None: ...
