from mutagen.id3._frames import APIC as APIC

class ID3:
    def add(self, frame: object) -> None: ...
    def getall(self, key: str) -> list[APIC]: ...
    def clear(self) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> object: ...
