class APIC:
    encoding: int
    mime: str
    type: int
    desc: str
    data: bytes
    def __init__(
        self,
        encoding: int = ...,
        mime: str = ...,
        type: int = ...,  # noqa: A002
        desc: str = ...,
        data: bytes = ...,
    ) -> None: ...

class _TextFrame:
    encoding: int
    text: list[str]
    def __init__(self, encoding: int = ..., text: str | list[str] = ...) -> None: ...
    def __str__(self) -> str: ...

class TALB(_TextFrame): ...
class TCOM(_TextFrame): ...
class TCON(_TextFrame): ...
class TCOP(_TextFrame): ...
class TDRC(_TextFrame): ...
class TDRL(_TextFrame): ...
class TIT2(_TextFrame): ...
class TMED(_TextFrame): ...
class TPE1(_TextFrame): ...
class TPE2(_TextFrame): ...
class TPE4(_TextFrame): ...
class TPOS(_TextFrame): ...
class TPUB(_TextFrame): ...
class TRCK(_TextFrame): ...
class TSOP(_TextFrame): ...

class TXXX:
    encoding: int
    desc: str
    text: list[str]
    def __init__(
        self, encoding: int = ..., desc: str = ..., text: str | list[str] = ...
    ) -> None: ...
